### PR TITLE
Added CSS to constrain size of iframe, object, and embed objects.

### PR DESCRIPTION
**Pull request by nickdotreid**
Issue #258 needed someway to control size of video embeds in content. This fix controls the width of the object.

A better fix would just target video objects, but I'm not really sure where the content is coming from...

### CODE REVIEW

**Comment by LukeSwart** [comment]
Hey @nickdotreid ! Thanks for this contribution, and I am super excited to test it out. Solving this issue will definitely improve the user experience when viewing our landmarks with videos.

If interested, here is a quick explanation about where the content is coming from:

The content for our landmarks comes from our Mapbox project as GeoJSON. For example, here is the content for our Restoration Sites: https://k7b7dyc4v3.execute-api.us-west-2.amazonaws.com/production/mapbox/landmarks?url=http://a.tiles.mapbox.com/v4/smartercleanup.k9dcl2i9/features.json?access_token=pk.eyJ1Ijoic21hcnRlcmNsZWFudXAiLCJhIjoiTnFhUWc2cyJ9.CqPJH-9yspIMudowQJx2Uw
(on a side note, we are also piping the Mapbox content through an AWS API Gateway, which helps us pre-process the Mapbox content)

And we can create a page for each feature in that GeoJSON collection by loading the html under the feature's `property.description` field. Here is the location of that Backbone view where the context is loaded: https://github.com/smartercleanup/platform/blob/master/src/sa_web/static/js/views/landmark-detail-view.js#L16-L22

And let me know if you have questions! I am happy to clarify anything. Feel free to join our chat channel as well.

**Comment by nickdotreid** [comment]
Oh, this is a silly question: where is the chat channel?

**Comment by LukeSwart** [comment]
Actually, there are almost too many chat channels! So it can be confusing. I just sent you an invite to our Chatgrape channel, but you can also reach us at https://openseattle.slack.com/ or #heyduwamish on Freenode too. Most of our activity tends to be on Chatgrape, but I'm usually signed into IRC and OpenSeattle too.

**Comment by LukeSwart** [comment]
Thank you sir! Your changes are now live ;)

**Pull request merged**
